name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Шаг 1: Клонирование репозитория

    - name: Set up Python
      uses: actions/setup-python@v2  # Шаг 2: Установка Python
      with:
        python-version: '3.x'  # Указываем версию Python (например, 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Обновление pip
        pip install -r requirements.txt  # Установка зависимостей из requirements.txt
        
    - name: Run unit tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE  # Добавляем корневую директорию в PYTHONPATH
        python -m unittest discover -s tests  # Запуск тестов через unittest

    - name: Run pytest
      run: |
        python -m pytest  # Запуск тестов через pytest